#!/bin/bash
set -ex

# recover backup environment file
if [ -f "/opt/lomorage/etc/environment.bak" ]
then
  cp /opt/lomorage/etc/environment.bak /opt/lomorage/etc/environment
fi

chmod +x /opt/lomorage/bin/*

CUR_USER=`ls -ld /opt/lomorage/bin | awk -F' ' '{print $3}'`
CUR_GROUP=`ls -ld /opt/lomorage/bin | awk -F' ' '{print $4}'`

sudo chown $CUR_USER:$CUR_GROUP /opt/lomorage/bin/lomod /opt/lomorage/bin/lomoc

sudo sed -i "s/User=pi/User=$CUR_USER/g" /lib/systemd/system/lomod.service
sudo sed -i "s/pi/$CUR_USER/g" /etc/cron.daily/update-lomod

if [ $(systemctl is-enabled lomod) != 'enabled' ];  then
  systemctl enable lomod
fi
systemctl daemon-reload
systemctl restart lomod
