#!/bin/bash
set -ex

chmod +x /opt/lomorage/bin/*

CUR_USER=`ls -l /opt/lomorage/bin/lomod | awk -F' ' '{print $3}'`

sudo sed -i "s/User=pi/User=$CUR_USER/g" /lib/systemd/system/lomod.service
sudo sed -i "s/pi/$CUR_USER/g" /etc/cron.daily/update-lomod

if [ $(systemctl is-enabled lomod) != 'enabled' ];  then
  systemctl enable lomod
fi
systemctl daemon-reload
systemctl restart lomod
