#!/bin/bash

if [ -f "/lib/systemd/system/lomod.service" ]
then
  systemctl stop lomod
fi 

# backup database
if [ -f "/opt/lomorage/var/assets.db" ]
then
  cp /opt/lomorage/var/assets.db /opt/lomorage/var/assets.db.$(date +%m-%d-%y.%H.%M.%S)
fi

# backup environment file
if [ -f "/opt/lomorage/etc/environment" ]
then
  cp /opt/lomorage/etc/environment /opt/lomorage/etc/environment.bak
fi
